use std::fmt::Write;
use thiserror::Error;
use unistructgen_core::{IREnum, IRField, IRModule, IRStruct, IRType, IRTypeRef};

#[derive(Error, Debug)]
pub enum CodegenError {
    #[error("Rendering error: {0}")]
    RenderError(String),

    #[error("Format error: {0}")]
    FormatError(#[from] std::fmt::Error),
}

pub type Result<T> = std::result::Result<T, CodegenError>;

#[derive(Debug, Clone)]
pub struct RenderOptions {
    pub add_header: bool,
    pub add_clippy_allows: bool,
}

impl Default for RenderOptions {
    fn default() -> Self {
        Self {
            add_header: true,
            add_clippy_allows: true,
        }
    }
}

pub struct RustRenderer {
    options: RenderOptions,
}

impl RustRenderer {
    pub fn new(options: RenderOptions) -> Self {
        Self { options }
    }

    pub fn render(&self, module: &IRModule) -> Result<String> {
        let mut output = String::new();

        if self.options.add_header {
            writeln!(output, "// Generated by unistructgen v{}", env!("CARGO_PKG_VERSION"))?;
            writeln!(output, "// Do not edit this file manually")?;
            writeln!(output)?;
        }

        if self.options.add_clippy_allows {
            writeln!(output, "#![allow(dead_code)]")?;
            writeln!(output, "#![allow(unused_imports)]")?;
            writeln!(output)?;
        }

        for ty in &module.types {
            match ty {
                IRType::Struct(s) => {
                    self.render_struct(&mut output, s)?;
                    writeln!(output)?;
                }
                IRType::Enum(e) => {
                    self.render_enum(&mut output, e)?;
                    writeln!(output)?;
                }
            }
        }

        Ok(output)
    }

    fn render_struct(&self, output: &mut String, ir_struct: &IRStruct) -> Result<()> {
        // Doc comment
        if let Some(doc) = &ir_struct.doc {
            writeln!(output, "/// {}", doc)?;
        }

        // Derives
        if !ir_struct.derives.is_empty() {
            write!(output, "#[derive(")?;
            for (i, derive) in ir_struct.derives.iter().enumerate() {
                if i > 0 {
                    write!(output, ", ")?;
                }
                write!(output, "{}", derive)?;
            }
            writeln!(output, ")]")?;
        }

        // Additional attributes
        for attr in &ir_struct.attributes {
            writeln!(output, "#[{}]", attr)?;
        }

        writeln!(output, "pub struct {} {{", ir_struct.name)?;

        for field in &ir_struct.fields {
            self.render_field(output, field)?;
        }

        writeln!(output, "}}")?;

        Ok(())
    }

    fn render_field(&self, output: &mut String, field: &IRField) -> Result<()> {
        // Field doc
        if let Some(doc) = &field.doc {
            writeln!(output, "    /// {}", doc)?;
        }

        // Field attributes
        for attr in &field.attributes {
            writeln!(output, "    #[{}]", attr)?;
        }

        // Field definition
        writeln!(
            output,
            "    pub {}: {},",
            field.name,
            self.render_type(&field.ty)?
        )?;

        Ok(())
    }

    fn render_enum(&self, output: &mut String, ir_enum: &IREnum) -> Result<()> {
        // Doc comment
        if let Some(doc) = &ir_enum.doc {
            writeln!(output, "/// {}", doc)?;
        }

        // Derives
        if !ir_enum.derives.is_empty() {
            write!(output, "#[derive(")?;
            for (i, derive) in ir_enum.derives.iter().enumerate() {
                if i > 0 {
                    write!(output, ", ")?;
                }
                write!(output, "{}", derive)?;
            }
            writeln!(output, ")]")?;
        }

        writeln!(output, "pub enum {} {{", ir_enum.name)?;

        for variant in &ir_enum.variants {
            if let Some(doc) = &variant.doc {
                writeln!(output, "    /// {}", doc)?;
            }
            writeln!(output, "    {},", variant.name)?;
        }

        writeln!(output, "}}")?;

        Ok(())
    }

    fn render_type(&self, ty: &IRTypeRef) -> Result<String> {
        match ty {
            IRTypeRef::Primitive(p) => Ok(p.rust_type_name().to_string()),
            IRTypeRef::Option(inner) => {
                Ok(format!("Option<{}>", self.render_type(inner)?))
            }
            IRTypeRef::Vec(inner) => {
                Ok(format!("Vec<{}>", self.render_type(inner)?))
            }
            IRTypeRef::Named(name) => Ok(name.clone()),
            IRTypeRef::Map(key, value) => {
                Ok(format!(
                    "std::collections::HashMap<{}, {}>",
                    self.render_type(key)?,
                    self.render_type(value)?
                ))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use unistructgen_core::{IRField, PrimitiveKind};

    #[test]
    fn test_render_simple_struct() {
        let mut ir_struct = IRStruct::new("User".to_string());
        ir_struct.add_field(IRField::new(
            "id".to_string(),
            IRTypeRef::Primitive(PrimitiveKind::I64),
        ));
        ir_struct.add_field(IRField::new(
            "name".to_string(),
            IRTypeRef::Primitive(PrimitiveKind::String),
        ));

        let mut module = IRModule::new("test".to_string());
        module.add_type(IRType::Struct(ir_struct));

        let renderer = RustRenderer::new(RenderOptions::default());
        let output = renderer.render(&module).unwrap();

        assert!(output.contains("pub struct User"));
        assert!(output.contains("pub id: i64"));
        assert!(output.contains("pub name: String"));
    }

    #[test]
    fn test_render_optional_field() {
        let mut ir_struct = IRStruct::new("User".to_string());
        ir_struct.add_field(IRField::new(
            "email".to_string(),
            IRTypeRef::Option(Box::new(IRTypeRef::Primitive(PrimitiveKind::String))),
        ));

        let mut module = IRModule::new("test".to_string());
        module.add_type(IRType::Struct(ir_struct));

        let renderer = RustRenderer::new(RenderOptions::default());
        let output = renderer.render(&module).unwrap();

        assert!(output.contains("pub email: Option<String>"));
    }

    #[test]
    fn test_render_vec_field() {
        let mut ir_struct = IRStruct::new("User".to_string());
        ir_struct.add_field(IRField::new(
            "tags".to_string(),
            IRTypeRef::Vec(Box::new(IRTypeRef::Primitive(PrimitiveKind::String))),
        ));

        let mut module = IRModule::new("test".to_string());
        module.add_type(IRType::Struct(ir_struct));

        let renderer = RustRenderer::new(RenderOptions::default());
        let output = renderer.render(&module).unwrap();

        assert!(output.contains("pub tags: Vec<String>"));
    }
}
