[package]
name = "unistructgen"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true

[[bin]]
name = "unistructgen"
path = "src/main.rs"

[dependencies]
unistructgen-core = { path = "../core" }
unistructgen-json-parser = { path = "../parsers/json_parser" }
unistructgen-codegen = { path = "../codegen" }
anyhow.workspace = true
clap = { version = "4.5", features = ["derive"] }
