//! Builder pattern for RustRenderer configuration
//!
//! Provides a fluent API for configuring Rust code generation options.

use crate::codegen::{RenderOptions, RustRenderer};

/// Builder for creating a RustRenderer with fluent API
///
/// This builder provides a convenient way to configure rendering options
/// using method chaining.
///
/// # Examples
///
/// ```
/// use unistructgen::codegen::RustRendererBuilder;
///
/// let renderer = RustRendererBuilder::new()
///     .add_header(true)
///     .add_clippy_allows(true)
///     .build();
/// ```
#[derive(Debug, Clone)]
pub struct RustRendererBuilder {
    options: RenderOptions,
}

impl RustRendererBuilder {
    /// Create a new builder with default options
    ///
    /// # Examples
    ///
    /// ```
    /// use unistructgen::codegen::RustRendererBuilder;
    ///
    /// let builder = RustRendererBuilder::new();
    /// ```
    pub fn new() -> Self {
        Self {
            options: RenderOptions::default(),
        }
    }

    /// Enable or disable adding a generated file header
    ///
    /// When enabled, adds a comment like:
    /// ```text
    /// // Generated by unistructgen v0.1.0
    /// // Do not edit this file manually
    /// ```
    ///
    /// Default: `true`
    ///
    /// # Examples
    ///
    /// ```
    /// use unistructgen::codegen::RustRendererBuilder;
    ///
    /// let renderer = RustRendererBuilder::new()
    ///     .add_header(false)
    ///     .build();
    /// ```
    pub fn add_header(mut self, enable: bool) -> Self {
        self.options.add_header = enable;
        self
    }

    /// Enable or disable adding clippy allow attributes
    ///
    /// When enabled, adds:
    /// ```text
    /// #![allow(dead_code)]
    /// #![allow(unused_imports)]
    /// ```
    ///
    /// Default: `true`
    ///
    /// # Examples
    ///
    /// ```
    /// use unistructgen::codegen::RustRendererBuilder;
    ///
    /// let renderer = RustRendererBuilder::new()
    ///     .add_clippy_allows(false)
    ///     .build();
    /// ```
    pub fn add_clippy_allows(mut self, enable: bool) -> Self {
        self.options.add_clippy_allows = enable;
        self
    }

    /// Configure both header and clippy allows at once
    ///
    /// Convenience method for common configurations.
    ///
    /// # Examples
    ///
    /// ```
    /// use unistructgen::codegen::RustRendererBuilder;
    ///
    /// // Clean output without any annotations
    /// let renderer = RustRendererBuilder::new()
    ///     .with_annotations(false, false)
    ///     .build();
    /// ```
    pub fn with_annotations(mut self, header: bool, clippy_allows: bool) -> Self {
        self.options.add_header = header;
        self.options.add_clippy_allows = clippy_allows;
        self
    }

    /// Create a minimal renderer (no header, no clippy allows)
    ///
    /// Useful for embedding generated code or when you want clean output.
    ///
    /// # Examples
    ///
    /// ```
    /// use unistructgen::codegen::RustRendererBuilder;
    ///
    /// let renderer = RustRendererBuilder::new()
    ///     .minimal()
    ///     .build();
    /// ```
    pub fn minimal(mut self) -> Self {
        self.options.add_header = false;
        self.options.add_clippy_allows = false;
        self
    }

    /// Get the current options (useful for inspection)
    ///
    /// # Examples
    ///
    /// ```
    /// use unistructgen::codegen::RustRendererBuilder;
    ///
    /// let builder = RustRendererBuilder::new().add_header(false);
    /// let options = builder.options();
    /// assert!(!options.add_header);
    /// ```
    pub fn options(&self) -> &RenderOptions {
        &self.options
    }

    /// Build the RustRenderer with the configured options
    ///
    /// # Examples
    ///
    /// ```
    /// use unistructgen::codegen::RustRendererBuilder;
    ///
    /// let renderer = RustRendererBuilder::new()
    ///     .add_header(true)
    ///     .build();
    /// ```
    pub fn build(self) -> RustRenderer {
        RustRenderer::new(self.options)
    }
}

impl Default for RustRendererBuilder {
    fn default() -> Self {
        Self::new()
    }
}

impl RustRenderer {
    /// Create a builder for configuring a RustRenderer
    ///
    /// This is a convenience method that returns a new builder.
    ///
    /// # Examples
    ///
    /// ```
    /// use unistructgen::codegen::RustRenderer;
    ///
    /// let renderer = RustRenderer::builder()
    ///     .minimal()
    ///     .build();
    /// ```
    pub fn builder() -> RustRendererBuilder {
        RustRendererBuilder::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_builder_default() {
        let _renderer = RustRendererBuilder::new().build();
        let builder = RustRendererBuilder::new();
        let options = builder.options();

        assert!(options.add_header);
        assert!(options.add_clippy_allows);
    }

    #[test]
    fn test_builder_custom() {
        let _renderer = RustRendererBuilder::new()
            .add_header(false)
            .add_clippy_allows(false)
            .build();

        // Renderer created successfully
    }

    #[test]
    fn test_builder_minimal() {
        let _renderer = RustRendererBuilder::new()
            .minimal()
            .build();

        let builder = RustRendererBuilder::new().minimal();
        let options = builder.options();
        assert!(!options.add_header);
        assert!(!options.add_clippy_allows);
    }

    #[test]
    fn test_builder_fluent_api() {
        let _renderer = RustRenderer::builder()
            .with_annotations(true, false)
            .build();

        // Renderer created successfully
    }

    #[test]
    fn test_builder_options_inspection() {
        let builder = RustRendererBuilder::new()
            .add_header(false);

        let options = builder.options();
        assert!(!options.add_header);
        assert!(options.add_clippy_allows);
    }
}
