// main_v2.rs - The "After" state (Clean Code)
// Usage: Rename this to main.rs OR copy-paste content into main.rs

mod models; // This module is generated by unistructgen
use models::Transaction;
use std::fs;

fn main() {
    println!("--- Payment Processor v2.0 (UniStructGen) ---");

    // 1. Load Data
    let data = fs::read_to_string("data/transaction.json").expect("Unable to read file");

    // 2. Deserialize into Strong Types
    // No manual mapping. No string keys. One line.
    let tx: Transaction = serde_json::from_str(&data).expect("Invalid JSON format");

    // 3. Clean Access
    // transaction_id is a real Uuid type, not a String!
    println!("Transaction ID: {}", tx.transaction_id);
    
    // 4. Nested Objects
    // Payer is a Struct, not a Hash Map
    if let Some(payer) = &tx.payer {
        println!("Payer Email: {}", payer.email);
    }

    // 5. Working with Dates
    // created_at is chrono::DateTime, so we can format it easily
    println!("Created At: {}", tx.created_at.format("%Y-%m-%d %H:%M UTC"));

    // 6. Safe Math
    // amount is f64, not String or Value
    if let Some(amount) = tx.amount {
         let fee = amount * 0.029; // Simple 2.9% fee calc
         println!("Fee calculated: ${:.2}", fee);
    }
}
